// src/components/MonthlyChart.tsx
import { memo, forwardRef } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

interface MonthlyData {
  month: string;
  income: number;
  expenses: number;
}

interface MonthlyChartProps {
  data: MonthlyData[];
  onMonthClick?: (month: string) => void;
}

const formatMonth = (month: string) => {
  const [year, m] = month.split('-');
  const months = ['Ιαν', 'Φεβ', 'Μαρ', 'Απρ', 'Μαϊ', 'Ιουν', 'Ιουλ', 'Αυγ', 'Σεπ', 'Οκτ', 'Νοε', 'Δεκ'];
  return `${months[parseInt(m) - 1]} ${year.slice(2)}`;
};

const formatCurrency = (value: number) => {
  return new Intl.NumberFormat('el-GR', {
    style: 'currency',
    currency: 'EUR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
};

const CustomTooltip = forwardRef<HTMLDivElement, any>(({ active, payload, label }, ref) => {
  if (active && payload && payload.length) {
    return (
      <div ref={ref} className="bg-card border border-border rounded-lg shadow-lg p-3">
        <p className="font-medium text-foreground mb-2">{formatMonth(label)}</p>
        {payload.map((entry: any, index: number) => (
          <p key={index} className="text-sm" style={{ color: entry.color }}>
            {entry.name}: {formatCurrency(entry.value)}
          </p>
        ))}
        <p className="text-xs text-muted-foreground mt-2">Κάντε κλικ για φιλτράρισμα</p>
      </div>
    );
  }
  return null;
});

export const MonthlyChart = memo(function MonthlyChart({ data, onMonthClick }: MonthlyChartProps) {
  const handleClick = (data: any) => {
    if (data && data.activePayload && data.activePayload.length > 0 && onMonthClick) {
      onMonthClick(data.activePayload[0].payload.month);
    }
  };

  return (
    <Card className="col-span-full lg:col-span-2">
      <CardHeader>
        <CardTitle className="text-lg">Μηνιαία Σύνοψη</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="h-[300px]">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart
              data={data}
              margin={{ top: 10, right: 10, left: 0, bottom: 0 }}
              onClick={handleClick}
              className="cursor-pointer"
            >
              <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
              <XAxis
                dataKey="month"
                tickFormatter={formatMonth}
                className="text-xs fill-muted-foreground"
              />
              <YAxis
                tickFormatter={(v) => {
                  if (v >= 1000) {
                    return `€${(v / 1000).toFixed(1).replace(/\.0$/, '')}k`;
                  }
                  return `€${v}`;
                }}
                className="text-xs fill-muted-foreground"
              />
              <Tooltip content={<CustomTooltip />} />
              <Legend />
              <Bar
                dataKey="income"
                name="Έσοδα"
                fill="hsl(var(--chart-1))"
                radius={[4, 4, 0, 0]}
              />
              <Bar
                dataKey="expenses"
                name="Έξοδα"
                fill="hsl(var(--chart-2))"
                radius={[4, 4, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </CardContent>
    </Card>
  );
});

// vue-app/src/components/MonthlyChart.vue
<template>
  <v-card class="h-100" elevation="0" border>
    <v-card-title class="text-h6 font-weight-bold pa-6 pb-2">Μηνιαία Σύνοψη</v-card-title>
    <v-card-text class="pa-6 pt-2">
      <div style="height: 300px; position: relative;">
        <Bar :data="chartData" :options="chartOptions" />
      </div>
    </v-card-text>
  </v-card>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Bar } from 'vue-chartjs';
import {
  Chart as ChartJS,
  Title,
  Tooltip,
  Legend,
  BarElement,
  CategoryScale,
  LinearScale,
} from 'chart.js';

ChartJS.register(CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend);

interface MonthlyData {
  month: string;
  income: number;
  expenses: number;
}

const props = defineProps<{
  data: MonthlyData[];
  onMonthClick?: (month: string) => void;
}>();

const emit = defineEmits(['month-click']);

const formatMonth = (month: string) => {
  const [year, m] = month.split('-');
  const months = ['Ιαν', 'Φεβ', 'Μαρ', 'Απρ', 'Μαϊ', 'Ιουν', 'Ιουλ', 'Αυγ', 'Σεπ', 'Οκτ', 'Νοε', 'Δεκ'];
  return `${months[parseInt(m) - 1]} ${year.slice(2)}`;
};

const chartData = computed(() => ({
  labels: props.data.map(d => formatMonth(d.month)),
  datasets: [
    {
      label: 'Έσοδα',
      backgroundColor: '#0ea5e9', // sky-500
      data: props.data.map(d => d.income),
      borderRadius: 4,
      maxBarThickness: 60,
      barPercentage: 0.7,
      categoryPercentage: 0.8,
    },
    {
      label: 'Έξοδα',
      backgroundColor: '#6366f1', // indigo-500
      data: props.data.map(d => d.expenses),
      borderRadius: 4,
      maxBarThickness: 60,
      barPercentage: 0.7,
      categoryPercentage: 0.8,
    },
  ],
}));

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  interaction: {
    mode: 'index' as any,
    intersect: false,
  },
  onClick: (_: any, elements: any) => {
    if (elements.length > 0) {
      const index = elements[0].index;
      const month = props.data[index].month;
      emit('month-click', month);
    }
  },
  scales: {
    y: {
      border: { display: false },
      grid: {
        color: '#f3f4f6', // gray-100
      },
      ticks: {
        callback: (value: any) => {
          if (value >= 1000) {
            return `€${(value / 1000).toFixed(1).replace(/\.0$/, '')}k`;
          }
          return `€${value}`;
        },
        font: { size: 11, family: 'Inter' },
        color: '#6b7280' // gray-500
      },
    },
    x: {
      grid: { display: false },
      ticks: {
        font: { size: 11, family: 'Inter' },
        color: '#6b7280' // gray-500
      }
    }
  },
  plugins: {
    legend: {
      position: 'bottom' as const,
      labels: {
        usePointStyle: true,
        boxWidth: 8,
        font: { size: 12, family: 'Inter' },
        color: '#374151' // gray-700
      }
    },
    tooltip: {
      backgroundColor: 'rgba(255, 255, 255, 0.95)',
      titleColor: '#000',
      bodyColor: '#666',
      borderColor: '#e5e7eb',
      borderWidth: 1,
      padding: 12,
      cornerRadius: 8,
      callbacks: {
        label: (context: any) => {
          let label = context.dataset.label || '';
          if (label) {
            label += ': ';
          }
          if (context.parsed.y !== null) {
            label += new Intl.NumberFormat('el-GR', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(context.parsed.y);
          }
          return label;
        }
      }
    }
  }
};
</script>

<style scoped>
.v-card {
  border-radius: 0.5rem !important;
}
</style>
